# Generated by Django 4.2.4 on 2023-09-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0004_remove_veiculo_categoria_remove_veiculo_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='capa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='garagem.modelo'),
        ),
    ]
