# Generated by Django 4.1.7 on 2023-03-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_veículo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veículo',
            new_name='Veiculo',
        ),
    ]
